# Generated by Django 5.2 on 2025-05-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
