# Generated by Django 5.2 on 2025-05-14 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chaifolder/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('Type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KW', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELAICHI')], max_length=2)),
            ],
        ),
    ]
